networks:
  network_1:
    driver: bridge

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4001:80"
    networks:
      - "network_1"

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4002:3000"
    networks:
      - "network_1"

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_password_segura
      POSTGRES_DB: nombre_base_datos
    ports:
      - "4003:5432"
    networks:
      - "network_1"
